version: '3.8'

services:
  web:
    build:
      context: .
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "20s", "node", "app.js"]
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  server:
    build:
      context: .
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "20s", "node", "backend/app.js"]
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: mysql:8.0.36
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql 
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app-network

networks:
app-network:
  driver: bridge

volumes:
  db_data: